test/osd: fix the link of the rollback clone reproducer
ghobject_t::NO_GEN is declared in the class with no out of line
definition, and it is const, not constexpr, thus it is not implicitly
inline. ASSERT_NE binds its arguments to const references, which
odr-uses the member:

  undefined reference to `ghobject_t::NO_GEN'
  in testing::internal::CmpHelperNE<unsigned long, unsigned long>

Keep a copy of the value in the test and use that copy.

Signed-off-by: Shraddha Agrawal <shraddha.agrawal000@gmail.com>